In [1]:
import pandas as pd

In [2]:
data = {"State": ["Ohio", "Ohio", "Ohio", "Texas", "Texas", "Texas", "kolkata", "kolkata", "kolkata"], "Year": [2000,2001,2002,2001,2002,2003,2001,2002,2003], "PoP": [1.5,1.6,3.6,2.4,2.9,3.2,2.6,2.8,3.4]}

frame = pd.DataFrame(data)

In [3]:
frame

     State  Year  PoP
0     Ohio  2000  1.5
1     Ohio  2001  1.6
2     Ohio  2002  3.6
3    Texas  2001  2.4
4    Texas  2002  2.9
5    Texas  2003  3.2
6  kolkata  2001  2.6
7  kolkata  2002  2.8
8  kolkata  2003  3.4

In [4]:
frame.head()

   State  Year  PoP
0   Ohio  2000  1.5
1   Ohio  2001  1.6
2   Ohio  2002  3.6
3  Texas  2001  2.4
4  Texas  2002  2.9

In [5]:
frame.tail()

     State  Year  PoP
4    Texas  2002  2.9
5    Texas  2003  3.2
6  kolkata  2001  2.6
7  kolkata  2002  2.8
8  kolkata  2003  3.4

In [6]:
pd.DataFrame(data, columns = ["Year", "State", "PoP"])

   Year    State  PoP
0  2000     Ohio  1.5
1  2001     Ohio  1.6
2  2002     Ohio  3.6
3  2001    Texas  2.4
4  2002    Texas  2.9
5  2003    Texas  3.2
6  2001  kolkata  2.6
7  2002  kolkata  2.8
8  2003  kolkata  3.4

In [7]:
frame2 = pd.DataFrame(data, columns = ["Year", "State", "PoP", "debt"])

In [8]:
frame2

   Year    State  PoP debt
0  2000     Ohio  1.5  NaN
1  2001     Ohio  1.6  NaN
2  2002     Ohio  3.6  NaN
3  2001    Texas  2.4  NaN
4  2002    Texas  2.9  NaN
5  2003    Texas  3.2  NaN
6  2001  kolkata  2.6  NaN
7  2002  kolkata  2.8  NaN
8  2003  kolkata  3.4  NaN

In [9]:
frame2.columns

Index(['Year', 'State', 'PoP', 'debt'], dtype='str')

In [10]:
frame2.State

0       Ohio
1       Ohio
2       Ohio
3      Texas
4      Texas
5      Texas
6    kolkata
7    kolkata
8    kolkata
Name: State, dtype: str

In [11]:
frame2["State"]

0       Ohio
1       Ohio
2       Ohio
3      Texas
4      Texas
5      Texas
6    kolkata
7    kolkata
8    kolkata
Name: State, dtype: str

In [12]:
frame2.Year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
6    2001
7    2002
8    2003
Name: Year, dtype: int64

In [13]:
frame2.loc[1]

Year     2001
State    Ohio
PoP       1.6
debt      NaN
Name: 1, dtype: object

In [14]:
frame2.loc[2]

Year     2002
State    Ohio
PoP       3.6
debt      NaN
Name: 2, dtype: object

In [15]:
frame2.loc[2,3]

KeyError: 3

In [ ]:
frame2.iloc[2,3]

In [ ]:
frame2.iloc[2,1]

In [ ]:
frame2["debt"] = "13M"

In [ ]:
frame2

In [16]:
frame2["debt"] = [45,2,3,4,51,45,2,1,53]

In [17]:
frame2

   Year    State  PoP  debt
0  2000     Ohio  1.5    45
1  2001     Ohio  1.6     2
2  2002     Ohio  3.6     3
3  2001    Texas  2.4     4
4  2002    Texas  2.9    51
5  2003    Texas  3.2    45
6  2001  kolkata  2.6     2
7  2002  kolkata  2.8     1
8  2003  kolkata  3.4    53

In [18]:
frame2["debt"] = [45,2,3,4,51,45,2,1]

ValueError: Length of values (8) does not match length of index (9)

In [19]:
 val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

In [20]:
frame2["debt"] = val

In [21]:
frame2

   Year    State  PoP  debt
0  2000     Ohio  1.5   NaN
1  2001     Ohio  1.6   NaN
2  2002     Ohio  3.6   NaN
3  2001    Texas  2.4   NaN
4  2002    Texas  2.9   NaN
5  2003    Texas  3.2   NaN
6  2001  kolkata  2.6   NaN
7  2002  kolkata  2.8   NaN
8  2003  kolkata  3.4   NaN

In [22]:
 val = pd.Series([-1.2, -1.5, -1.7], index=[2,4,5])

In [23]:
frame2["debt"] = val

In [24]:
frame2

   Year    State  PoP  debt
0  2000     Ohio  1.5   NaN
1  2001     Ohio  1.6   NaN
2  2002     Ohio  3.6  -1.2
3  2001    Texas  2.4   NaN
4  2002    Texas  2.9  -1.5
5  2003    Texas  3.2  -1.7
6  2001  kolkata  2.6   NaN
7  2002  kolkata  2.8   NaN
8  2003  kolkata  3.4   NaN

In [25]:
frame2["eastern"] = frame2["State"] == "Ohio"

In [26]:
frame2

   Year    State  PoP  debt  eastern
0  2000     Ohio  1.5   NaN     True
1  2001     Ohio  1.6   NaN     True
2  2002     Ohio  3.6  -1.2     True
3  2001    Texas  2.4   NaN    False
4  2002    Texas  2.9  -1.5    False
5  2003    Texas  3.2  -1.7    False
6  2001  kolkata  2.6   NaN    False
7  2002  kolkata  2.8   NaN    False
8  2003  kolkata  3.4   NaN    False

In [27]:
frame2.State

0       Ohio
1       Ohio
2       Ohio
3      Texas
4      Texas
5      Texas
6    kolkata
7    kolkata
8    kolkata
Name: State, dtype: str

In [28]:
frame2.eastern

0     True
1     True
2     True
3    False
4    False
5    False
6    False
7    False
8    False
Name: eastern, dtype: bool

In [29]:
del frame2["eastern"]

In [30]:
frame2.columns

Index(['Year', 'State', 'PoP', 'debt'], dtype='str')