In [15]:
import pandas as pd

In [16]:
import numpy as np

In [17]:
obj = pd.Series(np.arange(3), index = ["b", "a", "c"])

In [18]:
index = obj.index

In [19]:
index

Index(['b', 'a', 'c'], dtype='str')

In [20]:
index[1:]

Index(['a', 'c'], dtype='str')

In [21]:
index[1] = "b"

TypeError: Index does not support mutable operations

In [22]:
labels = pd.Index(np.arange(4))

In [23]:
labels

Index([0, 1, 2, 3], dtype='int64')

In [24]:
content = pd.Index([1,3,5,7])

In [25]:
obj2 = pd.Series([1.2,3.4,-5.6,2.1], index = content)

In [26]:
obj2

1    1.2
3    3.4
5   -5.6
7    2.1
dtype: float64

In [27]:
obj2.index is labels

False

In [28]:
frame3

NameError: name 'frame3' is not defined

In [30]:
population = {"ohio": {2000: 1.5, 2001:1.7, 2002:3.6}, "navada": {2001:2.4,2002:2.9}}

In [32]:
frame3 = pd.DataFrame(population)

In [33]:
frame3

      ohio  navada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [34]:
frame3.index.name = "year"
frame3.columns.name =  "state"

In [35]:
frame3

state  ohio  navada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [36]:
frame3.columns

Index(['ohio', 'navada'], dtype='str', name='state')

In [38]:
frame3.index

Index([2000, 2001, 2002], dtype='int64', name='year')

In [39]:
pd.Index(["foo","foo","faa","faa"])

Index(['foo', 'foo', 'faa', 'faa'], dtype='str')